// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "mrcox_types.h"
#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// fit_aligned
Rcpp::List fit_aligned(Rcpp::NumericMatrix X, Rcpp::NumericMatrix status, Rcpp::IntegerMatrix rankmin, Rcpp::IntegerMatrix rankmax, Rcpp::List order_list, Rcpp::NumericMatrix B0, Rcpp::NumericVector lambda_1_all, Rcpp::NumericVector lambda_2_all, VectorXd pfac, double step_size, int niter, double linesearch_beta, double eps, bool debug);
RcppExport SEXP _mrcox_fit_aligned(SEXP XSEXP, SEXP statusSEXP, SEXP rankminSEXP, SEXP rankmaxSEXP, SEXP order_listSEXP, SEXP B0SEXP, SEXP lambda_1_allSEXP, SEXP lambda_2_allSEXP, SEXP pfacSEXP, SEXP step_sizeSEXP, SEXP niterSEXP, SEXP linesearch_betaSEXP, SEXP epsSEXP, SEXP debugSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type status(statusSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix >::type rankmin(rankminSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix >::type rankmax(rankmaxSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type order_list(order_listSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type B0(B0SEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type lambda_1_all(lambda_1_allSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type lambda_2_all(lambda_2_allSEXP);
    Rcpp::traits::input_parameter< VectorXd >::type pfac(pfacSEXP);
    Rcpp::traits::input_parameter< double >::type step_size(step_sizeSEXP);
    Rcpp::traits::input_parameter< int >::type niter(niterSEXP);
    Rcpp::traits::input_parameter< double >::type linesearch_beta(linesearch_betaSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    Rcpp::traits::input_parameter< bool >::type debug(debugSEXP);
    rcpp_result_gen = Rcpp::wrap(fit_aligned(X, status, rankmin, rankmax, order_list, B0, lambda_1_all, lambda_2_all, pfac, step_size, niter, linesearch_beta, eps, debug));
    return rcpp_result_gen;
END_RCPP
}
// compute_dual_norm
VectorXd compute_dual_norm(MatrixXd grad, double alpha, double tol);
RcppExport SEXP _mrcox_compute_dual_norm(SEXP gradSEXP, SEXP alphaSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MatrixXd >::type grad(gradSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_dual_norm(grad, alpha, tol));
    return rcpp_result_gen;
END_RCPP
}
// compute_residual
MatrixXd compute_residual(Rcpp::NumericMatrix X, Rcpp::NumericMatrix status, Rcpp::IntegerMatrix rankmin, Rcpp::IntegerMatrix rankmax, Rcpp::List order_list, MatrixXd v);
RcppExport SEXP _mrcox_compute_residual(SEXP XSEXP, SEXP statusSEXP, SEXP rankminSEXP, SEXP rankmaxSEXP, SEXP order_listSEXP, SEXP vSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type status(statusSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix >::type rankmin(rankminSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix >::type rankmax(rankmaxSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type order_list(order_listSEXP);
    Rcpp::traits::input_parameter< MatrixXd >::type v(vSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_residual(X, status, rankmin, rankmax, order_list, v));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_mrcox_fit_aligned", (DL_FUNC) &_mrcox_fit_aligned, 14},
    {"_mrcox_compute_dual_norm", (DL_FUNC) &_mrcox_compute_dual_norm, 3},
    {"_mrcox_compute_residual", (DL_FUNC) &_mrcox_compute_residual, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_mrcox(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
