# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fit_aligned <- function(X, status, rankmin, rankmax, order_list, B0, lambda_1_all, lambda_2_all, pfac, step_size = 1.0, niter = 2000L, linesearch_beta = 1.1) {
    .Call(`_mrcox_fit_aligned`, X, status, rankmin, rankmax, order_list, B0, lambda_1_all, lambda_2_all, pfac, step_size, niter, linesearch_beta)
}

#' @export
compute_dual_norm <- function(grad, alpha, tol) {
    .Call(`_mrcox_compute_dual_norm`, grad, alpha, tol)
}

#' @export
compute_residual <- function(X, status, rankmin, rankmax, order_list, v) {
    .Call(`_mrcox_compute_residual`, X, status, rankmin, rankmax, order_list, v)
}

